---
on: 
  push:
    branches: 
      - main

jobs:
  # Define your jobs here
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Show calculated version
        run: echo "GitVersion calculated version: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Install Build Module
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: |
          # The -OutputPath is important for the next step
          Build-Module -Path $PSScriptRoot -Version ${{ steps.gitversion.outputs.fullSemVer }} -OutputPath ./Output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./Output