---
on: 
  push:
    branches: 
      - main

jobs:
  # Define your jobs here
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Module
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: |
          Build-Module $PSScriptRoot

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./Output